<?php
/**
 * @file
 * jdt_user_notes.module
 * This file includes hooks for permissions and other.
 */

/**
 * Implements jdt_user_notes_permissions().
 */
function jdt_user_notes_permission() {
  return array(
    'jdt_user_notes' => array(
      'title' => t('Administer jdt user notes module'),
      'description' => t('Perform administration tasks for jdt_user_notes modules.'),
    ),
  );
}

/**
 * Implements jdt_user_notes_simpletest().
 */
function jdt_user_notes_simpletest() {
  $dir = drupal_get_path('module', 'jdt_user_notes');
  $tests = file_scan_directory($dir, '\.test$');
  return array_keys($tests);
}
